from enum import Enum


class PODCategory(str, Enum):
    CLEAN_POD_SEAL_AND_SIGNATURE = "CLEAN_POD_SEAL_AND_SIGNATURE"
    CLEAN_POD_ONLY_SEAL = "CLEAN_POD_ONLY_SEAL"
    CLEAN_POD_ONLY_SIGNATURE = "CLEAN_POD_ONLY_SIGNATURE"
    ISSUE_POD_DAMAGED = "ISSUE_POD_DAMAGED"
    ISSUE_POD_SHORT = "ISSUE_POD_SHORT"
    ISSUE_POD_DAMAGED_AND_SHORT = "ISSUE_POD_DAMAGED_AND_SHORT"
    NO_SIGNATURE_NO_STAMP = "NO_SIGNATURE_NO_STAMP"
    MANUAL_CHECK_REQUIRED = "MANUAL_CHECK_REQUIRED"